# Generated by Django 5.2.8 on 2025-11-17 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the memory map', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the map and its purpose')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this map is publicly visible')),
                ('center_lat', models.FloatField(help_text='Latitude of the map center (-90 to 90)', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('center_lng', models.FloatField(help_text='Longitude of the map center (-180 to 180)', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('zoom_level', models.IntegerField(default=10, help_text='Default zoom level (1-20, where 1 is world view)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this map was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this map was last updated')),
                ('owner', models.ForeignKey(help_text='User who created and owns this map', on_delete=django.db.models.deletion.CASCADE, related_name='memory_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Map',
                'verbose_name_plural': 'Memory Maps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='memory_maps_owner_i_759e13_idx'), models.Index(fields=['is_public', '-created_at'], name='memory_maps_is_publ_840ac8_idx')],
            },
        ),
    ]
