# Generated by Django 5.2.8 on 2025-11-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon')], help_text='Type of geographic feature (point or polygon)', max_length=10)),
                ('geometry', models.TextField(help_text='GeoJSON geometry representation (fallback for non-PostGIS)')),
                ('title', models.CharField(help_text='Title or name of this feature', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this feature')),
                ('category', models.CharField(blank=True, help_text="Category or type classification (e.g., 'permaculture', 'amenity')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feature was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this feature was last updated')),
                ('map', models.ForeignKey(help_text='The map this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='memory_maps.map')),
            ],
            options={
                'verbose_name': 'Map Feature',
                'verbose_name_plural': 'Map Features',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['map', '-created_at'], name='memory_maps_map_id_971537_idx'), models.Index(fields=['feature_type'], name='memory_maps_feature_4308f1_idx'), models.Index(fields=['category'], name='memory_maps_categor_49d201_idx')],
            },
        ),
    ]
