# Generated by Django 5.2.8 on 2025-11-27 00:17

import django.db.models.deletion
import memory_maps.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_maps', '0002_mapfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The photo image file', upload_to=memory_maps.models.photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this photo was uploaded')),
                ('feature', models.ForeignKey(help_text='The map feature this photo is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memory_maps.mapfeature')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this photo', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['feature', '-uploaded_at'], name='memory_maps_feature_cdfaa7_idx'), models.Index(fields=['uploaded_by', '-uploaded_at'], name='memory_maps_uploade_147a59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the story', max_length=200)),
                ('content', models.TextField(help_text='The story content/narrative')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this story was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this story was last updated')),
                ('author', models.ForeignKey(help_text='User who wrote this story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(help_text='The map feature this story is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='memory_maps.mapfeature')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', '-created_at'], name='memory_maps_feature_355c6b_idx'), models.Index(fields=['author', '-created_at'], name='memory_maps_author__b8a037_idx')],
            },
        ),
    ]
